using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using System.Xml.Linq;
using System.IO.Compression;
using System.Text.Json;
using OpenUtau.Core.Ustx;

namespace OpenUtau.Api.Utils;

public static class SimpleExporters
{
    // VSQX Export
    public static void ExportVsqx(UProject project, UVoicePart part, string filePath)
    {
        var ns = XNamespace.Get("http://www.yamaha.co.jp/vocaloid/schema/vsq4/");
        var doc = new XDocument(
            new XDeclaration("1.0", "UTF-8", "no"),
            new XElement(ns + "vsq4",
                new XElement(ns + "vender", "Yamaha corporation"),
                new XElement(ns + "version", "4.0.0.3"),
                new XElement(ns + "vVoiceTable",
                    new XElement(ns + "vVoice",
                        new XElement(ns + "vBS", 0),
                        new XElement(ns + "vPC", 0)
                    )
                ),
                new XElement(ns + "mixer",
                    new XElement(ns + "masterUnit",
                        new XElement(ns + "outDev", 0),
                        new XElement(ns + "retLevel", 0),
                        new XElement(ns + "vol", 0)
                    ),
                    new XElement(ns + "vsUnit",
                        new XElement(ns + "tNo", 0),
                        new XElement(ns + "inGain", 0),
                        new XElement(ns + "sendLevel", 0),
                        new XElement(ns + "sendEnable", 0),
                        new XElement(ns + "mute", 0),
                        new XElement(ns + "solo", 0),
                        new XElement(ns + "pan", 64),
                        new XElement(ns + "vol", 0)
                    )
                ),
                new XElement(ns + "masterTrack",
                    new XElement(ns + "seqName", project.name),
                    new XElement(ns + "comment", "Exported from OpenUtau API"),
                    new XElement(ns + "resolution", project.resolution),
                    new XElement(ns + "preMeasure", 1),
                    new XElement(ns + "timeSig",
                        new XElement(ns + "posMes", 0),
                        new XElement(ns + "nume", project.timeSignatures.Any() ? project.timeSignatures[0].beatPerBar : 4),
                        new XElement(ns + "denomi", project.timeSignatures.Any() ? project.timeSignatures[0].beatUnit : 4)
                    ),
                    new XElement(ns + "tempo",
                        new XElement(ns + "posTick", 0),
                        new XElement(ns + "bpm", (int)((project.tempos.Any() ? project.tempos[0].bpm : 120) * 100))
                    )
                ),
                new XElement(ns + "vsTrack",
                    new XElement(ns + "tNo", 0),
                    new XElement(ns + "name", part.name),
                    new XElement(ns + "comment", "Track generated by OpenUtau API"),
                    new XElement(ns + "musicalPart",
                        new XElement(ns + "posTick", part.position),
                        new XElement(ns + "playTime", part.notes.Any() ? part.notes.Last().End : 1920),
                        new XElement(ns + "partName", part.name),
                        new XElement(ns + "comment", "Musical Part generated by OpenUtau API"),
                        new XElement(ns + "stylePlugin",
                            new XElement(ns + "stylePluginID", "ACA9C502-A04B-42b5-B2EB-5CEA36D16FCE"),
                            new XElement(ns + "stylePluginName", "VOCALOID2 Compatible Style"),
                            new XElement(ns + "version", "3.0.0.1")
                        ),
                        new XElement(ns + "partStyle",
                            new XElement(ns + "attr", new XAttribute("id", "accent"), 50),
                            new XElement(ns + "attr", new XAttribute("id", "bendDep"), 8),
                            new XElement(ns + "attr", new XAttribute("id", "bendLen"), 0),
                            new XElement(ns + "attr", new XAttribute("id", "decay"), 50),
                            new XElement(ns + "attr", new XAttribute("id", "fallPort"), 0),
                            new XElement(ns + "attr", new XAttribute("id", "opening"), 127),
                            new XElement(ns + "attr", new XAttribute("id", "risePort"), 0)
                        ),
                        new XElement(ns + "singer",
                            new XElement(ns + "posTick", 0),
                            new XElement(ns + "vBS", 0),
                            new XElement(ns + "vPC", 0)
                        ),
                        part.notes.Select(note => 
                            new XElement(ns + "note",
                                new XElement(ns + "posTick", note.position),
                                new XElement(ns + "durTick", note.duration),
                                new XElement(ns + "noteNum", note.tone),
                                new XElement(ns + "velocity", 64),
                                new XElement(ns + "lyric", note.lyric),
                                new XElement(ns + "phnms", new XAttribute("lock", 0), "a"),
                                new XElement(ns + "noteStyle",
                                    new XElement(ns + "attr", new XAttribute("id", "accent"), 50),
                                    new XElement(ns + "attr", new XAttribute("id", "bendDep"), 8),
                                    new XElement(ns + "attr", new XAttribute("id", "bendLen"), 0),
                                    new XElement(ns + "attr", new XAttribute("id", "decay"), 50),
                                    new XElement(ns + "attr", new XAttribute("id", "fallPort"), 0),
                                    new XElement(ns + "attr", new XAttribute("id", "opening"), 127),
                                    new XElement(ns + "attr", new XAttribute("id", "risePort"), 0)
                                )
                            )
                        )
                    )
                )
            )
        );
        doc.Save(filePath);
    }

    // MusicXML Export
    public static void ExportMusicXML(UProject project, UVoicePart part, string filePath)
    {
        var doc = new XDocument(
            new XDeclaration("1.0", "UTF-8", "no"),
            new XDocumentType("score-partwise", "-//Recordare//DTD MusicXML 3.1 Partwise//EN", "http://www.musicxml.org/dtds/partwise.dtd", null),
            new XElement("score-partwise", new XAttribute("version", "3.1"),
                new XElement("part-list",
                    new XElement("score-part", new XAttribute("id", "P1"),
                        new XElement("part-name", part.name)
                    )
                ),
                new XElement("part", new XAttribute("id", "P1"),
                    new XElement("measure", new XAttribute("number", "1"),
                        new XElement("attributes",
                            new XElement("divisions", project.resolution), // resolution is usually ticks per beat
                            new XElement("clef",
                                new XElement("sign", "G"),
                                new XElement("line", "2")
                            )
                        ),
                        part.notes.Select(note => 
                            new XElement("note",
                                new XElement("pitch",
                                    new XElement("step", GetNoteName(note.tone)),
                                    new XElement("octave", (note.tone / 12) - 1)
                                ),
                                new XElement("duration", note.duration),
                                new XElement("type", "quarter"),
                                new XElement("lyric",
                                    new XElement("syllabic", "single"),
                                    new XElement("text", note.lyric)
                                )
                            )
                        )
                    )
                )
            )
        );
        doc.Save(filePath);
    }

    private static string GetNoteName(int tone)
    {
        string[] names = { "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B" };
        return names[tone % 12].Replace("#", "");
    }

    // VPR Export
    public static void ExportVpr(UProject project, UVoicePart part, string filePath)
    {
        var vpr = new
        {
            version = "5.0.0",
            vendor = "Yamaha corporation",
            title = project.name,
            masterTrack = new
            {
                seqName = project.name,
                resolution = project.resolution,
                tempo = new { events = project.tempos.Select(t => new { pos = t.position, value = t.bpm * 100 }) },
                timeSig = new { events = project.timeSignatures.Select(t => new { pos = t.barPosition, numerator = t.beatPerBar, denominator = t.beatUnit }) }
            },
            voices = new[]
            {
                new { compID = "vID", name = "Default Voice" }
            },
            tracks = new[]
            {
                new {
                    type = 0,
                    name = part.name,
                    parts = new[] {
                        new {
                            pos = part.position,
                            duration = part.notes.Any() ? part.notes.Last().End : 1920,
                            voice = new { compID = "vID" },
                            notes = part.notes.Select(note => new {
                                pos = note.position,
                                duration = note.duration,
                                number = note.tone,
                                lyric = note.lyric,
                                velocity = 64
                            })
                        }
                    }
                }
            }
        };

        string json = JsonSerializer.Serialize(vpr, new JsonSerializerOptions { WriteIndented = true });
        
        using (var archive = ZipFile.Open(filePath, ZipArchiveMode.Create))
        {
            var entry = archive.CreateEntry("Project/sequence.json");
            using (var writer = new StreamWriter(entry.Open()))
            {
                writer.Write(json);
            }
        }
    }
}
